

-- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS FULLDAY_SCAPE;

-- CREATE USER TABLE
CREATE TABLE IF NOT EXISTS FULLDAY_SCAPE.USUARIOS (
    ID int NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    MAIL VARCHAR(200) NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)
    
);

-- CREATE PACKAGES TABLE 
CREATE TABLE IF NOT EXISTS FULLDAY_SCAPE.PAQUETES (
ID int NOT NULL,
TITULO VARCHAR(200) NOT NULL,
CHECK_IN DATETIME NOT NULL,
CHECK_OUT DATETIME NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
PRECIO FLOAT NOT NULL,
CONSTRAINT PK_PAQUETES PRIMARY KEY (ID)
);

-- CREATE BOOKINS TABLE
CREATE TABLE IF NOT EXISTS FULLDAY_SCAPE.RESERVAS (
ID int NOT NULL, 
PRECIO FLOAT NOT NULL, 
CHECK_IN DATETIME NOT NULL,
CHECK_OUT DATETIME NOT NULL,
USER_ID int NOT NULL, 
PAQUETES_ID int NOT NULL,
CONSTRAINT PK_RESERVAS PRIMARY KEY (ID),
CONSTRAINT FK_RESERVAS_USER FOREIGN KEY (USER_ID) REFERENCES USUARIOS(ID),
CONSTRAINT FK_RESERVAS_PAQUETES FOREIGN KEY (PAQUETES_ID) REFERENCES PAQUETES(ID)
);



-- CREATE PROMOTIONS TABLE 
CREATE TABLE  IF NOT EXISTS FULLDAY_SCAPE.PROMOCIONES (
ID int NOT NULL,
NOMBRE VARCHAR(200) NOT NULL,
PORCENTAJE FLOAT NOT NULL,
CONSTRAINT PK_PROMOCIONES PRIMARY KEY (ID)
);

-- CREATE SERVICES TABLE 
CREATE TABLE  IF NOT EXISTS FULLDAY_SCAPE.SERVICIOS (
ID int NOT NULL,
NOMBRE VARCHAR(200) NOT NULL,
CONSTRAINT PK_SERVICIOS PRIMARY KEY (ID)
);

-- CREATE TABLE PAQUETES - PROMOCIONES
 CREATE TABLE  IF NOT EXISTS FULLDAY_SCAPE.PAQUETES_PROMOCIONES (
  ID INT PRIMARY KEY,
  PAQUETE_ID INT,
  PROMOCION_ID INT,
  FOREIGN KEY (PAQUETE_ID) REFERENCES PAQUETES(ID),
  FOREIGN KEY (PROMOCION_ID) REFERENCES PROMOCIONES(ID)
 );
 
 -- CREATE TABLE PAQUETES - SERVICIOS 
 CREATE TABLE  IF NOT EXISTS FULLDAY_SCAPE.PAQUETES_SERVICIOS (
 ID INT PRIMARY KEY,
 PAQUETE_ID INT,
 SERVICIOS_ID INT,paquetes_promociones
 FOREIGN KEY (PAQUETE_ID) REFERENCES PAQUETES(ID),
 FOREIGN KEY (SERVICIOS_ID) REFERENCES SERVICIOS(ID)
 );
 
 

 
 
 
 
 
 
 
 
 
 




