
-- LINEA PARA DARLE PERMISOS SOLO DE LECTURA EL PRIMER USUARIO
GRANT SELECT ON fullday_scape.* TO 'usuario_lectura'@'localhost';
-- LINEA PARA DARLE PERMISOS DE LECTURA ESCRITURA Y MODIFICACION AL SEGUNDO USUARIO
GRANT SELECT, INSERT, UPDATE ON fullday_scape.* TO 'usuario_escritura'@'localhost';


-- LINEA PARA APLICAR LOS PERMSISOS 
FLUSH PRIVILEGES;